### ISSUE TITLE
Support Glide 4.11.0

### ISSUE THREAD

**Issue by Nstd** [wasabeef/glide-transformations#182]
# Bug Reporting
This library is using glide 4.9.0 now. When I upgrade glide version to 4.11.0 in my project, I got this error:
``` java
GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
    java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:344)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:336)
        at com.bumptech.glide.Glide.get(Glide.java:179)
        at kt.api.tools.glide.GlideApp.get(GlideApp.java:52)
        at kt.api.tools.glide.ImageLoad.trimMemory(ImageLoad.java:582)
```

## OS details

- Device:
- OS:

*Please add relevant labels*

**Comment by Nstd** [comment]
My fault. Compiler version is not the same as glide version.
