### ISSUE TITLE
Error on using Blur transformation on some devices [java.lang.UnsatisfiedLinkError]

### ISSUE THREAD

**Issue by vinaywadhwa** [wasabeef/glide-transformations#29]
I get this exception on Samsung Galaxy Note 2 only. 

onException(android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "librsjni.so", http://myapp.com/image_url.jpg, Target for: android.support.v7.widget.AppCompatImageView{66ff4da V.ED.... ........ 0,0-1440,896 #7f1102d9 app:id/backdrop}, true)
                                          android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.reado.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "librsjni.so"
                                              at android.support.v8.renderscript.RenderScript.internalCreate(RenderScript.java:1347)
                                              at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1504)
                                              at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1454)
                                              at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1430)
                                              at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1417)
                                              at jp.wasabeef.glide.transformations.BlurTransformation.transform(BlurTransformation.java:95)
                                              at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
                                              at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
                                              at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
                                              at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
                                              at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                              at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                              at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:818)
                                              at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)

This looks related - https://code.google.com/p/android/issues/detail?id=182356

Is this a known issue? Do we have a workaround for this?

**Comment by samy-baili** [comment]
I got the same problem here , there is a solution ?

**Comment by wasabeef** [comment]
@vinaywadhwa @samy-baili 

Fix 1.4.0 :sheep:

**Comment by samy-baili** [comment]
Got this error, during apt generation: 
Error:duplicate files during packaging of APK 

You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'lib/armeabi-v7a/libRSSupport.so'
	  }
	}
The same error with those files :
exclude 'lib/armeabi-v7a/libblasV8.so'
exclude 'lib/armeabi-v7a/librsjni.so'

**Comment by wasabeef** [comment]
@samy-baili 

Sorry..
try  2.0.0

**Comment by samy-baili** [comment]
Fixed :+1: 
Thank you very much
