### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by alvarlagerlof** [wasabeef/glide-transformations#50]
Please help me! Sometimes I get this error 

`E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                            java.lang.Throwable: Explicit termination method 'destroy' not called
                                                                                at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                                at android.renderscript.Script.<init>(Script.java:374)
                                                                                at android.renderscript.ScriptIntrinsic.<init>(ScriptIntrinsic.java:29)
                                                                                at android.renderscript.ScriptIntrinsicBlur.<init>(ScriptIntrinsicBlur.java:30)
                                                                                at android.renderscript.ScriptIntrinsicBlur.create(ScriptIntrinsicBlur.java:49)
                                                                                at jp.wasabeef.glide.transformations.internal.RSBlur.blur(RSBlur.java:41)
                                                                                at jp.wasabeef.glide.transformations.BlurTransformation.transform(BlurTransformation.java:93)
                                                                                at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
                                                                                at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
                                                                                at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
                                                                                at com.bumptech.glide.load.engine.DecodeJob.decodeSourceFromCache(DecodeJob.java:113)
                                                                                at com.bumptech.glide.load.engine.EngineRunnable.decodeFromCache(EngineRunnable.java:116)
                                                                                at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:99)
                                                                                at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)`

This is my code
`// Load image
            Glide.with(context)
                    .load("https://api.temadagar.ravla.org/" + context.getResources().getString(R.string.API_VERSION) + "/get_image.php?w=300&h=225&id=" + id)
                    .diskCacheStrategy(DiskCacheStrategy.ALL)
                    .thumbnail( 0.5f )
                    .placeholder(R.raw.day_holder)
                    .into(((ViewHolderGrid) holder).image);`

Please I need help! It's urgent

**Comment by etby** [comment]
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                              java.lang.Throwable: Explicit termination method 'destroy' not called
                                                                  at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                  at android.renderscript.Script.<init>(Script.java:345)
                                                                  at android.renderscript.ScriptIntrinsic.<init>(ScriptIntrinsic.java:29)
                                                                  at android.renderscript.ScriptIntrinsicBlur.<init>(ScriptIntrinsicBlur.java:30)
                                                                  at android.renderscript.ScriptIntrinsicBlur.create(ScriptIntrinsicBlur.java:50)
                                                                  at jp.wasabeef.glide.transformations.internal.RSBlur.blur(RSBlur.java:41)
                                                                  at jp.wasabeef.glide.transformations.BlurTransformation.transform(BlurTransformation.java:93)
                                                                  at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperTransformation.transform(GifBitmapWrapperTransformation.java:34)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.transform(DecodeJob.java:236)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.transformEncodeAndTranscode(DecodeJob.java:139)
                                                                  at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:129)
                                                                  at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
                                                                  at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
                                                                  at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                  at java.lang.Thread.run(Thread.java:761)
                                                                  at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

in `jp.wasabeef.glide.transformations.internal.RSBlur.blur(RSBlur.java:41)`

```
public class RSBlur {

  @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR2)
  public static Bitmap blur(Context context, Bitmap bitmap, int radius) throws RSRuntimeException {
    RenderScript rs = null;
    try {
      rs = RenderScript.create(context);
      rs.setMessageHandler(new RenderScript.RSMessageHandler());
      Allocation input =
          Allocation.createFromBitmap(rs, bitmap, Allocation.MipmapControl.MIPMAP_NONE,
              Allocation.USAGE_SCRIPT);
      Allocation output = Allocation.createTyped(rs, input.getType());
      ScriptIntrinsicBlur blur = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));
     
      blur.setInput(input);
      blur.setRadius(radius);
      blur.forEach(output);
      output.copyTo(bitmap);
    } finally {
      if (rs != null) {
        rs.destroy();
      }
    }

    return bitmap;
  }
}
```
RenderScript is destoryed, but ScriptIntrinsicBlur is not destoryed.

**Comment by RosesJack** [comment]
As far as I know,it not just destory  RenderScript  and ScriptIntrinsicBlur , also to destory  2 Allocation.

**Comment by HizkiaLemuel** [comment]
Is there any solution? I get this error too
@RosesJack @etby @alvarlagerlof
